### ISSUE TITLE
Not support file  from  url? 

### ISSUE THREAD

**Issue by Tamicer** [pavlospt/RxFile#11]
not support from  web url?

**Comment by pavlospt** [comment]
If you read the description of the repository it says: *Rx methods to get a File and Image or Video thumbnails from a Document Provider on Android (Drive, Dropbox etc).* This library is used in order to manipulate files internally on the Android. It is not a file download library :)

**Comment by Tamicer** [comment]
@pavlospt  I see,  thanks
