### ISSUE TITLE
Always a NullPointerException on Android API less than 19

### ISSUE THREAD

**Issue by JM-Agrimap** [pavlospt/RxFile#8]
DocumentFile.fromSingleUri causes a NullPointerException as it always returns null if android API is under 19.

```
private static File fileFromUri(Context context, Uri data) throws Exception {
        DocumentFile file = DocumentFile.fromSingleUri(context,data);
        String fileType = file.getType();
...
}
```

**Comment by pavlospt** [comment]
The `minSdkVersion` of the Library is API 19. Please use it if you target API 19 or higher.

**Comment by JM-Agrimap** [comment]
Your default config indicates a minimum version of 15, I see that a previous issue asked you to make it lower. Either they didn't test it or something has changed.

It may be a good idea to document this in you README.

**Comment by pavlospt** [comment]
``` java
public static DocumentFile fromSingleUri(Context context, Uri singleUri) {
        final int version = Build.VERSION.SDK_INT;
        if (version >= 19) {
            return new SingleDocumentFile(null, context, singleUri);
        } else {
            return null;
        }
    }
```

Apparently it seems that below API level 19, they return null by default. I am not quite sure when this was changed, but I increased the `minSdkVersion`  of the library because of it. Will upload it later on the day on Maven and jCenter.

**Comment by princeHago** [comment]
it possibile retrive a DocumentFile from InputStream/ByteArrayOutputStream/byte[]?
