### ISSUE TITLE
Don't add support RTL in application tag

### ISSUE THREAD

**Issue by Kisty** [pavlospt/RxFile#9]
Just added this app and we don't support RTL at present as our app is training material for the UK. Can you remove the `supportsRtl` attribute from the `application` in AndroidManifest.xml?

I can replace setting using tools as advised but it would prevent friction for other users.

```
Error:Execution failed for task ':app:processDevDebugManifest'.
> Manifest merger failed : Attribute application@supportsRtl value=(false) from AndroidManifest.xml:13:9-36
	is also present at [com.github.pavlospt:rxfile:1.5] AndroidManifest.xml:16:9-35 value=(true).
	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:3:5-18:19 to override.
```

**Comment by Kisty** [comment]
Applies to the other attributes. I'd suggest having a clear `application` tag. Am cooking up a PR.

**Comment by Kisty** [comment]
CI build failed and can't rebuild from this end. I think it failed from downloading a dependency. Any chance you can trigger a build? I did it by doing the following but there must be a better way. 
`Project settings` -> `Test environment` -> `Test settings on... master` > `Save & Go`

**Comment by pavlospt** [comment]
I rerun it manually and it seems to pass now. Something odd might have happened on the previous run.

**Comment by Kisty** [comment]
That's cool. Odd it happened. Thanks for dealing with it!

**Comment by pavlospt** [comment]
No problem thanks for the PR as well!
